import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import adminAuthRouter from "./admin_auth";
import investorRouter from "./investor";
import adminInvestorsRouter from "./admin_investors";
import vehicleListingsRouter from "./vehicle_listings";
import clientsRouter from "./clients";
import contractTemplatesRouter from "./contract_templates";
import seedRouter from "./seed";
import contactRouter from "./contact";
import blogRouter from "./blog";
import partnersRouter from "./partners";
import storageRouter from "./storage";
import reservationsRouter from "./reservations";
import webauthnRouter from "./webauthn";
import driverTrackingRouter from "./driver_tracking";
import mapsRouter from "./maps";
import soroAiRouter from "./soro_ai";
import deployDownloadRouter from "./deploy_download";
import logoProxyRouter from "./logo_proxy";
import anonFavoritesRouter from "./anon_favorites";
import unsubscribeRouter from "./unsubscribe";
import feedbackRouter from "./feedback";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(authRouter);
router.use(adminAuthRouter);
router.use(investorRouter);
router.use(adminInvestorsRouter);
router.use(vehicleListingsRouter);
router.use(clientsRouter);
router.use(contractTemplatesRouter);
router.use(seedRouter);
router.use(contactRouter);
router.use(blogRouter);
router.use(partnersRouter);
router.use(reservationsRouter);
router.use(webauthnRouter);
router.use(driverTrackingRouter);
router.use(mapsRouter);
router.use(soroAiRouter);
router.use(deployDownloadRouter);
router.use(logoProxyRouter);
router.use(anonFavoritesRouter);
router.use(unsubscribeRouter);
router.use(feedbackRouter);

export default router;
